FLAGS = -pedantic-errors -std=c++11

input.o: input.h
    g++ $(FLAGS) -c $<

process.o: process.h
    g++ $(FLAGS) -c $<

output.o: output.h
    g++ $(FLAGS) -c $<

Leaderboard.o: Leaderboard.h
    g++ $(FLAGS) -c $<

main.o: main.cpp input.h process.h output.h Leaderboard.h
    g++ $(FLAGS) -c $<

main: main.o input.o process.o output.o Leaderboard.o
    g++ $(FLAGS) $^ -o $@

clean:
    rm -f gcd input.o process.o output.o Leaderboard.o main.o input.tgz process.tgz output.tgz

tar:
    tar -czvf main.tgz *.cpp *.h

.PHONY: clean tar
